apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: microservices-tickets
build:
  local:
    push: false
  artifacts:
  - image: ivanmitkov/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    -  ./infra/k8s/*
